#!/bin/bash

function shouldInstall() {
  if ! [ -d node_modules ] ; then
    return 0
  fi

  return 1
}


cd back
if shouldInstall ; then
  yarn
fi

if ! npm test
then
  exit 1
fi

cd ../front
if shouldInstall ; then
  yarn
fi
if ! npm test
then
  exit 1
fi
