version: '3.7'

services:

  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - crdb
    depends_on:
      - crdb

  crdb:
    image: cockroachdb/cockroach:latest-v21.2
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - cockroach:/cockroach/cockroach-data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  cockroach: