env:
  browser: true
  es2021: true
settings:
  react:
    version: "detect"
  import/resolver:
    typescript: {}
extends:
  - '@remix-run/eslint-config'
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/recommended
plugins:
  - prettier
overrides:
  - files: '**/*.test.[jt]s?(x)'
    env:
      jest/globals: true
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
      - plugin:jest/style
      - plugin:jest-dom/recommended
      - plugin:testing-library/react

  - files: '**/*.ts?(x)'
    extends:
      - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
    parserOptions:
      project:
        - './tsconfig.json'
    rules:
      'jsx-a11y/alt-text': 'off'
      '@typescript-eslint/consistent-type-assertions': error
      '@typescript-eslint/consistent-type-exports': error
      '@typescript-eslint/return-await': error
      '@typescript-eslint/prefer-ts-expect-error': error
      '@typescript-eslint/prefer-reduce-type-parameter': error
      '@typescript-eslint/non-nullable-type-assertion-style': error

      '@typescript-eslint/restrict-template-expressions': 'off'
      '@typescript-eslint/no-unsafe-assignment': 'off'
      '@typescript-eslint/no-unsafe-member-access': 'off'
      '@typescript-eslint/no-unsafe-argument': 'off'
      '@typescript-eslint/no-unsafe-call': 'off'
      '@typescript-eslint/no-unsafe-return': 'off'
      '@typescript-eslint/no-floating-promises': 'off'
      '@typescript-eslint/no-misused-promises':
        - error
        - checksVoidReturn: false
rules:
  'curly':
    - error
    - multi-line
    - consistent
  'prettier/prettier': warn

  'import/named': error
  'import/no-useless-path-segments': error
  'import/newline-after-import': error
  'import/no-named-default': error
  '@typescript-eslint/prefer-optional-chain': error

  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/no-var-requires': 'off'
  '@typescript-eslint/no-non-null-assertion': 'off'
  '@typescript-eslint/no-empty-function': 'off'
  '@typescript-eslint/ban-ts-comment': 'off'
  '@typescript-eslint/no-extra-semi': 'off'
  'prefer-const':
    - error
    - destructuring: all
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
      ignoreRestSiblings: true