name: pull-request

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.13.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
      - run: bash actions-scripts/install
      
      - name: Run lint
        run: bash actions-scripts/lint
      
      - name: Start a CockroachDB Instance
        run: |
          cd back
          whoami
          docker compose up -d crdb
          
      - name: Wait for DB
        uses: aamadeo27/wait-for-it-action@master
        with:
          host: localhost
          port: 26257

      - name: Set up DB
        run: bash actions-scripts/setup-db
      - name: Run Tests
        run: bash actions-scripts/test
