name: pull-request

on: pull_request

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 15.x
        uses: actions/setup-node@v3
        with:
          node-version: 15.x
      - run: bash actions-scripts/install
      
      - name: Run lint
        run: bash actions-scripts/lint
      
      - name: Start a CockroachDB Instance
        run: |
          sudo docker pull cockroachdb/cockroach:latest-v21.2
          cd back
          sudo docker compose up -d crdb
          wait-for-it -h localhost -p 26257

      - name: Set up DB
        run: bash actions-scripts/setup-db
      - name: Run Tests
        run: bash actions-scripts/test